
toolchain=g++
bin_destination_path =..
TARGET=Server
SOURCE=server.cpp server_main.cpp

.PHONY : all
all: $(TARGET)
	
$(TARGET):
	$(toolchain) $(SOURCE) -o $(bin_destination_path)/$(TARGET) -lpthread

	@echo
	@echo Server Build sucessfully!



	






























